### ISSUE TITLE
400 - Invalid client_id

### ISSUE THREAD

**Issue by JulioFaustino** [iTwin/unreal-engine-3dft-plugin#11]
Hi,
I keep finding this error once I "play" the iModel Selection-Menu level in Unreal Engine.

I've already edited the iTwinAuthorizationService.cpp file with the line containing the Client-ID:
static constexpr auto iTwinAppId = TEXT("native-pJ4<.........>hTY1kbjYRPzZy");

Any help with that, please?

**Comment by kowac666** [comment]
Hello,

I'm having the same issue.

**Comment by danieliborra** [comment]
Hello,

it is possible that UE didn't recompile the plugin after the change?

Try deleting the folders `Plugins\iTwin\Binaries` and `Plugins\iTwin\Intermediate`.
This "forces" UE to recompile the plugin the next time you open the project.

Best regards,
Daniel

**Comment by JulioFaustino** [comment]
Hi Daniel,
That was the solution! It finally worked
Thank you so much and congrats for your work.
 Best regards,
JULIO

**Comment by danieliborra** [comment]
Thank you very much Julio!

I'll include this tip in the documentation so your feedback can help other users.

Don't hesitate to share your progress with the plugin.

Best regards,
Daniel

**Comment by kowac666** [comment]
Thanks Daniel!
I finally have this working. 
Cheers,
Chris

**Comment by danieliborra** [comment]
That's great, thank you!
