### ISSUE TITLE
The following modules are missing or built with a different engine version

### ISSUE THREAD

**Issue by StuartKeelingWSP** [iTwin/unreal-engine-3dft-plugin#13]
When I try and open the iTwin example project I recieve the following error message:

The following modules are missing or built with a different engine version:
iTwin Example
iTwin
Would you like to rebuild them 

after hitting yes, I get the following:

iTwinExample could not be compiled. Try rebuilding from source manually

**Comment by danieliborra** [comment]
Hello,

Which platform are you using, Mac or Windows?
Have you installed the correct version of XCode or Visual Studio? (Unreal requires installing one of those in order to use a plugin)

Daniel

**Comment by StuartKeelingWSP** [comment]
Hi Daniel,

I am using Windows, I have Visual Studio, as well as vsCode. Any help will be greatly appreciated 

Regards

Stuart

**Comment by danieliborra** [comment]
Hi Stuart,

ok, then there are many reasons why it can fail (missing dependencies, non-matching versions, etc etc).
You can reach me by email to schedule a call to dig into it deeper and find what is missing.

Best regards,
Daniel

**Comment by StuartKeelingWSP** [comment]
Hi Daniel,

thanks for getting back to me, could you please provide me with your email and I will get in contact there, alternatively reach out to me at stuart.keeling@wsp.com

many thanks, 

Stuart

**Comment by danieliborra** [comment]
Hi Stuart,

I'm glad you finally got it working by installing .net core 3.1.
Installing UE is always a little bit challenging.

Best regards,
Daniel
