### ISSUE TITLE
Obejects appearing really far away on start up.

### ISSUE THREAD

**Issue by Kzozuez** [iTwin/unreal-engine-3dft-plugin#15]
Hi
This might be a very rudimentary issue but it's always faster to just ask the question.
Why is it that some models appear right in front of the starting position while others are really far away?
Thanks

**Comment by danieliborra** [comment]
Hi,

that depends on the configuration of the iModels and if they are centred around the area of interest or not (their *extend* also affects it).

**Comment by Kzozuez** [comment]
Ok thanks, I assume the configuration should be done on the iTwin platform and not the desktop design application?
