### ISSUE TITLE
Editing imodel in Unreal

### ISSUE THREAD

**Issue by Kzozuez** [iTwin/unreal-engine-3dft-plugin#16]
Hi
Is it possible to add objects to the model in Unreal rather than having it sync with the iTwin platform? 
For example if I wanted better foliage in Unreal, can I add that somehow and not have it conflict with the iTwin model?
Thanks

**Comment by danieliborra** [comment]
Yes, of course, you can add objects to the level as with any other project.
If you want to remove certain parts of the iModel, you can remove them using the transform API (recommended) or do it manually element by element in the plugin.

**Comment by Kzozuez** [comment]
Ok interesting, thanks.
I ask becuse after I open the unreal project file it is essentially empty until I click the play button, I assumed that Unreal is only used for viewing and not intereacting/adding. 
I'll start with the Transform API then, thansk again.

**Comment by danieliborra** [comment]
There are two samples/levels, one for "dynamic loading" and one that let's you place and visualize the iModel in the editor itself.
There are some instructions to use it in the plugin repository.

**Comment by Kzozuez** [comment]
Halo again, could I trouble you to point me in the direction of the "dynamic loading" samples? I don't know where to look.. thanks! also where are the instructions exactly?

**Comment by Kzozuez** [comment]
Let's say I want to create the environment around the imodel within unreal, is there a way to do it while I can see the imodel in the viewer?

<img width="953" alt="Unreal Capture1" src="https://github.com/iTwin/unreal-engine-3dft-plugin/assets/66561904/77bb41f4-8e18-44d1-8862-d9d0ab61b6f9">

**Comment by danieliborra** [comment]
The level is called "Manual-iModel-Placement", it is one of the levels of the project.
The instructions are in main page of this repository, in the "Samples" section.

![image](https://github.com/iTwin/unreal-engine-3dft-plugin/assets/107669762/029c68a1-34b0-443c-8ac4-22bd81553699)

**Comment by Kzozuez** [comment]
Ok, much clearer now thanks

**Comment by danieliborra** [comment]
You're welcome!
