### ISSUE TITLE
glTF support

### ISSUE THREAD

**Issue by soularmindmedia** [iTwin/unreal-engine-3dft-plugin#19]
I read somewhere that iTwin platform has an alternative to 3DFT, which is using glTF. I believe this might be more suitable for my Metaverse solution right now since I would be able to manipulate the model a little easier in Unreal Engine.

I'm not sure how to access the glTF alternative, is there some documentation for that?

**Comment by danieliborra** [comment]
We are deprecating glTF, as it can only support small 3d models (infrastructure models tend to be very big).
